import { Branch, Subject, AcademicNote, StudentNotification, BrandingConfig, StudentUser, TeacherUser } from '../types';

export const INITIAL_BRANDING: BrandingConfig = {
  facultyName: 'P. DEVIKA',
  facultyTitle: 'Asst. Prof.',
  designation: 'ASSISTANT PROFESSOR',
  department: 'DEPT OF CSE(DS,CYS) AND AI&DS',
  institution: 'Vallurupalli Nageswara Rao Vignana Jyothi Institute of Engineering & Technology (VNRVJIET)',
  institutionShort: 'VNRVJIET',
  portalTitle: 'Academic Notes & Curriculum Portal',
  tagline: 'Official academic repository for CSE (DS, CyS) and AI & DS branch-wise curriculum material, unit notes, and lecture resources.',
  announcement: '📢 Official academic portal for VNRVJIET students. Unit-wise verified curriculum material uploaded directly by faculty.',
  contactEmail: 'p_devika@vnrvjiet.in',
  officeRoom: 'Department of CSE(DS, CyS) & AI&DS, Faculty Room 304',
  academicYear: 'Academic Year 2025-2026',
  regulation: 'R25 / Autonomous',
};

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'branch-cse',
    code: 'CSE',
    name: 'Computer Science and Engineering',
    shortName: 'CSE',
    category: 'Computing',
    description: 'Core computing, systems software, algorithms, and distributed computing architectures.',
    color: '#3B82F6',
    totalStudentsCount: 240,
  },
  {
    id: 'branch-cs-ds',
    code: 'CS-DS',
    name: 'CSE (Data Science)',
    shortName: 'CS-DS',
    category: 'Computing',
    description: 'Big data processing, statistical computing, predictive modeling, and data pipelines.',
    color: '#8B5CF6',
    totalStudentsCount: 180,
  },
  {
    id: 'branch-cs-aiml',
    code: 'CS-AIML',
    name: 'CSE (Artificial Intelligence & Machine Learning)',
    shortName: 'CS-AIML',
    category: 'Computing',
    description: 'Neural networks, deep learning architectures, intelligent reasoning, and computer vision.',
    color: '#EC4899',
    totalStudentsCount: 180,
  },
  {
    id: 'branch-ai-ds',
    code: 'AI & DS',
    name: 'Artificial Intelligence & Data Science',
    shortName: 'AI & DS',
    category: 'Computing',
    description: 'Integrated intelligence frameworks, deep analytics, and applied neural modeling.',
    color: '#06B6D4',
    totalStudentsCount: 120,
  },
  {
    id: 'branch-cs-cys',
    code: 'CS-CyS',
    name: 'CSE (Cyber Security)',
    shortName: 'CS-CyS',
    category: 'Computing',
    description: 'Network defense, cryptography, vulnerability analysis, and security governance.',
    color: '#EF4444',
    totalStudentsCount: 120,
  },
  {
    id: 'branch-cs-iot',
    code: 'CS-IOT',
    name: 'CSE (Internet of Things)',
    shortName: 'CS-IOT',
    category: 'Computing',
    description: 'Embedded sensory networks, edge computing, smart device telemetry, and hardware integration.',
    color: '#F97316',
    totalStudentsCount: 60,
  },
  {
    id: 'branch-csbs',
    code: 'CSBS',
    name: 'Computer Science and Business Systems',
    shortName: 'CSBS',
    category: 'Computing',
    description: 'Enterprise computing, business data modeling, software architecture, and financial systems.',
    color: '#10B981',
    totalStudentsCount: 60,
  },
  {
    id: 'branch-it',
    code: 'IT',
    name: 'Information Technology',
    shortName: 'IT',
    category: 'Computing',
    description: 'Web enterprise architectures, cloud infrastructure, database administrations, and network security.',
    color: '#0284C7',
    totalStudentsCount: 180,
  },
  {
    id: 'branch-ece',
    code: 'ECE',
    name: 'Electronics and Communication Engineering',
    shortName: 'ECE',
    category: 'Circuits & Systems',
    description: 'Digital signal processing, VLSI design, wireless communications, and microcontrollers.',
    color: '#6366F1',
    totalStudentsCount: 240,
  },
  {
    id: 'branch-ece-vlsi',
    code: 'ECE-VLSI',
    name: 'ECE (VLSI Design & Technology)',
    shortName: 'ECE-VLSI',
    category: 'Circuits & Systems',
    description: 'Semiconductor design, ASIC workflows, FPGA synthesis, and nanoscale circuit design.',
    color: '#4F46E5',
    totalStudentsCount: 60,
  },
  {
    id: 'branch-eee',
    code: 'EEE',
    name: 'Electrical and Electronics Engineering',
    shortName: 'EEE',
    category: 'Circuits & Systems',
    description: 'Power systems, electrical machines, high-voltage engineering, and control theory.',
    color: '#EAB308',
    totalStudentsCount: 120,
  },
  {
    id: 'branch-eie',
    code: 'EIE',
    name: 'Electronics and Instrumentation Engineering',
    shortName: 'EIE',
    category: 'Circuits & Systems',
    description: 'Sensors, industrial automation, biomedical instrumentation, and process control systems.',
    color: '#14B8A6',
    totalStudentsCount: 60,
  },
  {
    id: 'branch-me',
    code: 'ME',
    name: 'Mechanical Engineering',
    shortName: 'ME',
    category: 'Core Engineering',
    description: 'Thermodynamics, fluid mechanics, CAD/CAM, manufacturing processes, and robotics.',
    color: '#64748B',
    totalStudentsCount: 120,
  },
  {
    id: 'branch-ce',
    code: 'CE',
    name: 'Civil Engineering',
    shortName: 'CE',
    category: 'Core Engineering',
    description: 'Structural mechanics, geotechnical engineering, environmental systems, and surveying.',
    color: '#78716C',
    totalStudentsCount: 120,
  },
  {
    id: 'branch-ae',
    code: 'AE',
    name: 'Automobile Engineering',
    shortName: 'AE',
    category: 'Core Engineering',
    description: 'Vehicle dynamics, powertrain engineering, aerodynamics, and alternative fuel systems.',
    color: '#EA580C',
    totalStudentsCount: 60,
  },
  {
    id: 'branch-r-ai',
    code: 'R&AI',
    name: 'Robotics and Artificial Intelligence',
    shortName: 'R&AI',
    category: 'Applied Science',
    description: 'Kinematics, autonomous mobile robots, robotic vision, and cyber-physical systems.',
    color: '#9333EA',
    totalStudentsCount: 60,
  },
  {
    id: 'branch-bio-tech',
    code: 'Bio-Tech',
    name: 'Biotechnology',
    shortName: 'Bio-Tech',
    category: 'Applied Science',
    description: 'Bioinformatics, molecular genetics, bioprocess engineering, and computational biology.',
    color: '#059669',
    totalStudentsCount: 60,
  },
];

export const INITIAL_SUBJECTS: Subject[] = [
  // CSE Subjects
  {
    id: 'sub-cse-ds',
    branchId: 'branch-cse',
    code: 'CS301PC',
    name: 'Data Structures and Algorithms',
    semester: 'Semester 3',
    year: '2nd Year',
    description: 'Linear & non-linear data structures, trees, graphs, sorting, searching algorithms, and asymptotic complexity.',
    credits: 4,
    totalUnits: 5,
  },
  {
    id: 'sub-cse-dbms',
    branchId: 'branch-cse',
    code: 'CS302PC',
    name: 'Database Management Systems',
    semester: 'Semester 3',
    year: '2nd Year',
    description: 'Relational algebra, SQL, normalization theory, transactions, ACID properties, and indexing.',
    credits: 4,
    totalUnits: 5,
  },
  {
    id: 'sub-cse-os',
    branchId: 'branch-cse',
    code: 'CS401PC',
    name: 'Operating Systems',
    semester: 'Semester 4',
    year: '2nd Year',
    description: 'Process scheduling, concurrency synchronization, memory management, virtual memory, and file systems.',
    credits: 3,
    totalUnits: 5,
  },
  {
    id: 'sub-cse-cn',
    branchId: 'branch-cse',
    code: 'CS402PC',
    name: 'Computer Networks',
    semester: 'Semester 4',
    year: '2nd Year',
    description: 'OSI & TCP/IP stack, routing protocols, flow control, transport layer protocols, and network security.',
    credits: 3,
    totalUnits: 5,
  },

  // CS-DS (Data Science) Subjects
  {
    id: 'sub-csds-stat',
    branchId: 'branch-cs-ds',
    code: 'DS301PC',
    name: 'Applied Statistics & Probability for Data Science',
    semester: 'Semester 3',
    year: '2nd Year',
    description: 'Hypothesis testing, Bayesian inference, continuous distributions, multivariate regression, and Monte Carlo estimation.',
    credits: 4,
    totalUnits: 5,
  },
  {
    id: 'sub-csds-mining',
    branchId: 'branch-cs-ds',
    code: 'DS302PC',
    name: 'Data Mining and Warehousing',
    semester: 'Semester 3',
    year: '2nd Year',
    description: 'ETL pipelines, dimensional modeling, OLAP, association rule mining (Apriori), and clustering techniques.',
    credits: 4,
    totalUnits: 5,
  },
  {
    id: 'sub-csds-bigdata',
    branchId: 'branch-cs-ds',
    code: 'DS401PC',
    name: 'Big Data Technologies with Hadoop & Spark',
    semester: 'Semester 4',
    year: '2nd Year',
    description: 'HDFS ecosystem, MapReduce, Apache Spark RDDs/DataFrames, streaming analytics, and NoSQL databases.',
    credits: 3,
    totalUnits: 5,
  },

  // CS-AIML Subjects
  {
    id: 'sub-aiml-fai',
    branchId: 'branch-cs-aiml',
    code: 'AI301PC',
    name: 'Foundations of Artificial Intelligence',
    semester: 'Semester 3',
    year: '2nd Year',
    description: 'State space search, heuristic searches (A*, minimax), constraint satisfaction, knowledge representation, and first-order logic.',
    credits: 4,
    totalUnits: 5,
  },
  {
    id: 'sub-aiml-ml',
    branchId: 'branch-cs-aiml',
    code: 'AI302PC',
    name: 'Machine Learning Principles & Algorithms',
    semester: 'Semester 3',
    year: '2nd Year',
    description: 'Supervised & unsupervised learning, decision trees, support vector machines, gradient descent, and ensemble learning.',
    credits: 4,
    totalUnits: 5,
  },

  // AI & DS Subjects
  {
    id: 'sub-aids-deep',
    branchId: 'branch-ai-ds',
    code: 'AD301PC',
    name: 'Deep Learning & Neural Architectures',
    semester: 'Semester 3',
    year: '2nd Year',
    description: 'Feedforward neural networks, backpropagation, CNNs, RNNs, transformers, and regularization techniques.',
    credits: 4,
    totalUnits: 5,
  },

  // CS-CyS Subjects
  {
    id: 'sub-cys-crypto',
    branchId: 'branch-cs-cys',
    code: 'CY301PC',
    name: 'Cryptography and Network Security',
    semester: 'Semester 3',
    year: '2nd Year',
    description: 'Symmetric & asymmetric ciphers, RSA, AES, elliptic curve cryptography, digital signatures, and TLS.',
    credits: 4,
    totalUnits: 5,
  },

  // IT Subjects
  {
    id: 'sub-it-web',
    branchId: 'branch-it',
    code: 'IT301PC',
    name: 'Web Technologies & Cloud Architectures',
    semester: 'Semester 3',
    year: '2nd Year',
    description: 'Modern front-end frameworks, RESTful APIs, Node.js server architectures, microservices, and AWS basics.',
    credits: 4,
    totalUnits: 5,
  },

  // ECE Subjects
  {
    id: 'sub-ece-dsp',
    branchId: 'branch-ece',
    code: 'EC301PC',
    name: 'Digital Signal Processing',
    semester: 'Semester 3',
    year: '2nd Year',
    description: 'Discrete Fourier Transform (DFT), FFT algorithms, IIR and FIR filter design, and multirate DSP.',
    credits: 4,
    totalUnits: 5,
  },
  {
    id: 'sub-ece-vlsi',
    branchId: 'branch-ece',
    code: 'EC302PC',
    name: 'CMOS VLSI Design',
    semester: 'Semester 3',
    year: '2nd Year',
    description: 'MOSFET characteristics, CMOS inverter, layout rules, combinational circuit logic, and timing analysis.',
    credits: 4,
    totalUnits: 5,
  },

  // EEE Subjects
  {
    id: 'sub-eee-power',
    branchId: 'branch-eee',
    code: 'EE301PC',
    name: 'Power System Analysis & Grid Operations',
    semester: 'Semester 3',
    year: '2nd Year',
    description: 'Transmission line models, load flow studies (Gauss-Seidel, Newton-Raphson), fault analysis, and power stability.',
    credits: 4,
    totalUnits: 5,
  },

  // ME Subjects
  {
    id: 'sub-me-thermo',
    branchId: 'branch-me',
    code: 'ME301PC',
    name: 'Applied Thermodynamics & Heat Transfer',
    semester: 'Semester 3',
    year: '2nd Year',
    description: 'First and Second laws of thermodynamics, Otto/Diesel/Rankine cycles, conduction, convection, and radiation.',
    credits: 4,
    totalUnits: 5,
  },

  // CE Subjects
  {
    id: 'sub-ce-struct',
    branchId: 'branch-ce',
    code: 'CE301PC',
    name: 'Structural Analysis and Mechanics of Materials',
    semester: 'Semester 3',
    year: '2nd Year',
    description: 'Deflection of beams, moment distribution method, slope-deflection equations, and matrix stiffness analysis.',
    credits: 4,
    totalUnits: 5,
  },
];

// Clean empty notes array for official deployment - ready for real faculty uploads
export const INITIAL_NOTES: AcademicNote[] = [];

// Clean empty notifications for official deployment
export const INITIAL_NOTIFICATIONS: StudentNotification[] = [];

// Clean empty demo students
export const DEMO_STUDENTS: StudentUser[] = [];

export const DEMO_TEACHER: TeacherUser = {
  id: 'teacher-01',
  role: 'teacher',
  name: 'P. DEVIKA',
  employeeId: 'EMP-FAC-204',
  email: 'p_devika@vnrvjiet.in',
  designation: 'ASSISTANT PROFESSOR',
  department: 'DEPT OF CSE(DS,CYS) AND AI&DS',
  managedBranchIds: [
    'branch-cse',
    'branch-cs-ds',
    'branch-cs-aiml',
    'branch-ai-ds',
    'branch-cs-cys',
    'branch-cs-iot',
    'branch-csbs',
    'branch-it',
    'branch-ece',
    'branch-eee',
    'branch-me',
    'branch-ce',
  ],
  activeBranchId: 'branch-cse',
};
